feat(9): refactor players list page
berTrindade/video-player-manager pull request #61
Opened 2024-01-08 09:50 UTC by romansharapov19

- Add pagination to players list

2024-01-08 14:04 UTC, berTrindade commented
@romansharapov19, this issue is happening on your branch, so I created [this](https://github.com/berTrindade/video-player-manager/pull/63) PR that fixes it.

2024-01-08 14:37 UTC, leroybm approved these changes
LGTM

2024-01-09 16:23 UTC, leroybm requested changes

2024-01-09 16:23 UTC, leroybm commented on app/(app)/(dashboard)/players/page.tsx
> +        `http://localhost:3000/api/players?offset=${searchParams.page}`
Just checked that we have this on our env file, as to not hardcode it as localhost

2024-01-09 16:23 UTC, leroybm commented on app/(app)/(dashboard)/players/page.tsx
> +    await fetch(`http://localhost:3000/api/players/count`)
Just checked that we have this on our env file, as to not hardcode it as localhost

2024-01-10 09:31 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +  if (searchParams.page > 0) {
**suggestion: ** Instead of using a `let` variable above which is mutable. You could early return this condition to something like. E.g: 

`if (searchParams.page === 0) return`

Then you can switch `let` to `const`.

2024-01-10 09:51 UTC, berTrindade requested changes

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +  const [showPlayersFrom, setShowPlayersFrom] = useState(calculatePlayersFrom)
**thought:** You don't actually need to keep these calculations in a state variable (`showPlayersFrom` and `showPlayersTo`). The values are already calculated as the `searchParams` variable changes on each request.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +  useEffect(() => {
**thought:** You also might not need this `useEffect` to keep track of `currentPage` and syncing state. As the `searchParams` changes on every request, everything is calculated again.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +          onClick={onNextPage}
**suggestion:** Would be good thing to do is adding a disable state for the button based on the condition where `currentPage` is less than the limit/last page.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +    if (currentPage != Math.ceil(playersCount / limit)) {
**suggestion:** Could extract `Math.ceil(playersCount / limit)` to a const, e.g, `totalPages`.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +    currentPage === 1 ? 1 : limit * (currentPage - 1) + 1
**suggestion:**  Could extract `limit * (currentPage - 1) + 1` to a const called `offset`.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +  const calculatePlayersFrom =
**suggestion:** Since this component could be used in other places, you could rename `calculatePlayersFrom` and `calculatePlayersTo` to `startIndex` and `endIndex`.

2024-01-10 09:51 UTC, berTrindade commented on constants/pagination.ts
> +export const limit = 2
**suggestion:** It's usually a common practice to make constant uppercased.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +    if (currentPage != 1) {
**suggestion:** You could removed `!=` operators from both conditions and replaced it with `>` and `<` for better clarity.

2024-01-10 09:51 UTC, berTrindade commented on components/pagination.tsx
> +export function Pagination({ playersCount }: PaginationProps) {
suggestion: Since this component could be used in other places, you could rename this as `totalCount`.

2024-01-10 09:59 UTC, romansharapov19 commented on components/pagination.tsx
> +          onClick={onNextPage}
in that case we wont render the pagination because there are no players.

2024-01-10 10:02 UTC, berTrindade commented on components/pagination.tsx
> +    if (currentPage != 1) {
**suggestion:** You can also move the condition to a const. E.g: `const hasPrevious = currentPage > 1`.

2024-01-10 10:04 UTC, berTrindade commented on components/pagination.tsx
> +    if (currentPage != 1) {
**suggestion:** You can add `1` to a const `MIN_PAGE_NUMBER` and move it to the `constants` folder.

2024-01-10 10:06 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +      {players.length ?
**suggestion:** Could also early return `No Players To Display` message under the condition of `players.length === 0`.

2024-01-10 10:08 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +  const playersCount = await (
**suggestion:** Would be good to have a try-catch in case of error. You could use `useFetch` if you want or add the try-catch yourself.

2024-01-10 10:12 UTC, romansharapov19 commented on app/(app)/(dashboard)/players/page.tsx
> +  if (searchParams.page > 0) {
Nice catch!

2024-01-10 10:13 UTC, romansharapov19 commented on app/(app)/(dashboard)/players/page.tsx
> +  const playersCount = await (
Since this is the only place where this function will be used I just extract the fetch to a getPlayers function in the top of the file. What do you think about it?

2024-01-10 10:15 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +  const playersCount = await (
That works! Good one!

2024-01-10 10:26 UTC, romansharapov19 commented on components/pagination.tsx
> +          onClick={onNextPage}
did you click in the next page button or you change the URL?

2024-01-10 10:43 UTC, berTrindade commented on components/pagination.tsx
> +          onClick={onNextPage}
Clicked on the `Next` page button. Spot anything ?

2024-01-10 10:45 UTC, romansharapov19 commented on components/pagination.tsx
> +          onClick={onNextPage}
It should not work ... if you are in the last page the click in the button should do nothing

2024-01-10 10:47 UTC, romansharapov19 commented on app/(app)/(dashboard)/players/page.tsx
> +  if (searchParams.page > 0) {
it is a strategy, but in that case if a user change the url to 100 and the is no page 100 the user will receive incorrect data

2024-01-10 10:50 UTC, romansharapov19 commented on components/pagination.tsx
> +    currentPage === 1 ? 1 : limit * (currentPage - 1) + 1
it is not the offset and in this case I really don't have a name for it because it is the `showPlayersFrom`

2024-01-10 10:54 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +  if (searchParams.page > 0) {
Maybe, for that we could spin up a function to handle this scenarios. But if you think it's OK to use `let`, I'm OK.

2024-01-10 10:56 UTC, berTrindade commented on components/pagination.tsx
> +          onClick={onNextPage}
I tested again. Looks like it's doing what you said it would.

https://github.com/berTrindade/video-player-manager/assets/13338262/40450b9c-5788-48a2-b3eb-0a2dde30b5cd

But I think my point is more like greying the button or only the text to let the user know there's nothing left to go to.

2024-01-10 14:43 UTC, romansharapov19 commented on app/(app)/(dashboard)/players/page.tsx
> +      {players.length ?
In this case we will duplicate the title and the add button because if there is no users we will want to display the those two.

2024-01-10 14:58 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +      {players.length ?
True! It's fine.

2024-01-10 17:26 UTC, leroybm commented on components/pagination.tsx
> +  const showPlayersTo = LIMIT * currentPage
Would be nice to change the reference to players as this component is generic, like this
```suggestion
  const showItemFrom = LIMIT * (currentPage - 1) + 1
  const showItemTo = LIMIT * currentPage
```

2024-01-11 11:50 UTC, berTrindade commented on app/(app)/(dashboard)/players/page.tsx
> +const getPlayers = (page: number) =>
**suggestion:** Would be good to add an error handling mechanism, like a try-catch.

Usually, using `notFound` is a good approach. **Source:** https://nextjs.org/learn/dashboard-app/error-handling#handling-404-errors-with-the-notfound-function

In our codebase there's an example of that, which @leroybm implemented for [`EmbeddedVideo` component](https://github.com/leroybm/fp-manager/blob/996a0df98aa0d0370b78c5f044ec2be61e9cde79/app/(embed)/embed/%5Bid%5D/page.tsx#L16).

2024-01-11 15:55 UTC, berTrindade commented on components/pagination.tsx
> +  const showPlayersTo = LIMIT * currentPage
@romansharapov19, looks like `showItemFrom` isn't being used.

<img width="873" alt="image" src="https://github.com/berTrindade/video-player-manager/assets/13338262/02735569-1b01-4d1a-b628-12217adb1c56">

2024-01-11 16:25 UTC, berTrindade approved these changes
Awesome PR, @romansharapov19! 🥇💯

2024-01-11 18:48 UTC, leroybm approved these changes
Looks real good to me 🚀

2024-01-12 09:07 UTC, merged